#release configuration
#Thu Apr 30 08:59:46 CEST 2026
projectVersionPolicyId=default
project.scm.org.jahia.community\:content-reports-react.developerConnection=scm\:git\:git@github.com\:jahia/contentReportReact.git
remoteTagging=true
scm.commentPrefix=[skip ci] [maven-release-plugin]
project.dev.org.jahia.community\:content-reports-react=2.0.1-SNAPSHOT
completedPhase=end-release
project.scm.org.jahia.community\:content-reports-react.tag=HEAD
scm.url=scm\:git\:git@github.com\:jahia/contentReportReact.git
project.scm.org.jahia.community\:content-reports-react.connection=scm\:git\:git@github.com\:jahia/contentReportReact.git
project.rel.org.jahia.community\:content-reports-react=2.0.0
scm.tagNameFormat=@{project.artifactId}-@{project.version}
pushChanges=true
project.scm.org.jahia.community\:content-reports-react.url=https\://github.com/jahia/contentReportReact
scm.tag=content-reports-react-2.0.0
exec.snapshotReleasePluginAllowed=false
preparationGoals=clean install
