#release configuration
#Wed Apr 29 18:33:21 CEST 2026
projectVersionPolicyId=default
remoteTagging=true
scm.commentPrefix=[skip ci] [maven-release-plugin]
project.rel.org.jahia.community\:contentReportReact=1.1.0
project.scm.org.jahia.community\:contentReportReact.url=https\://github.com/jahia/contentReportReact
completedPhase=end-release
scm.url=scm\:git\:git@github.com\:jahia/contentReportReact.git
project.scm.org.jahia.community\:contentReportReact.connection=scm\:git\:git@github.com\:jahia/contentReportReact.git
scm.tagNameFormat=@{project.artifactId}-@{project.version}
pushChanges=true
project.scm.org.jahia.community\:contentReportReact.tag=HEAD
project.dev.org.jahia.community\:contentReportReact=1.1.1-SNAPSHOT
project.scm.org.jahia.community\:contentReportReact.developerConnection=scm\:git\:git@github.com\:jahia/contentReportReact.git
scm.tag=contentReportReact-1.1.0
exec.snapshotReleasePluginAllowed=false
preparationGoals=clean install
